site_name: "Narae Kuem"
theme:
  name: "material"
  logo: "assets/logo.png" # 로고 경로 설정
  favicon: "assets/favicon.ico" # 브라우저 탭 아이콘 변경 가능
  language: ko
  palette:
    scheme: default
    primary: "#28a745" # 강조 색상 변경 (여기서는 초록색)
    accent: "#007bff" # 보조 강조 색상 (파란색)
  font:
    text: "Noto Sans KR"
    code: "Fira Code"
  features:
    - navigation.top      # 상단 탭
    - navigation.sections # 탭마다 사이드바 분리
    
nav:
  - 소개:
      - 작가 소개: about/index.md
      - 작가 노트: about/notes.md
      - CV: about/cv.md
  - 작품:
      - 회화: works/paintings.md
      - 설치: works/installations.md
      - 영상: works/video.md
      - 게임/디지털: works/digital.md
  - 프로젝트:
      - 개인전: projects/solo.md
      - 협업: projects/collab.md
      - 출판물: projects/publications.md
  - 전시기록:
      - 2024: exhibitions/2024.md
      - 2023: exhibitions/2023.md
      - 이전: exhibitions/earlier.md

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/"

extra_css:
  - overrides/stylesheets/extra.css

copyright: "© 2023–<script>document.write(new Date().getFullYear())</script> Narae Kuem. All rights reserved."

extra_javascript:
  - overrides/collapsible.js

markdown_extensions:
  - admonition
  - footnotes
